### ISSUE TITLE
rpcx中文开发文档编写： 任务认领

### ISSUE THREAD

**Issue by smallnest** [smallnest/go-rpc-programming-guide#2]
参考英文文档 https://github.com/smallnest/rpcx-programming

# Summary

## Part Ⅰ 开发起步 by  solarhell (@雪球的铲屎官)
* [x] [快速起步](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/quickstart.md) 
* [x]  [服务端开发示例](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/server.md)
* [x]  [客户端开发示例](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/client.md)
* [x]  [传输](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/transport.md)
  * [x]  [TCP](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/tcp.md)
  * [x]  [HTTP](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/http.md)
  * [x]  [UnixDomain](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/unixdomain.md)
  * [x]  [QUIC](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/quic.md)
  * [x]  [KCP](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/kcp.md)
* [x]  [函数为服务](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part1/function.md)
## Part Ⅱ 注册中心 by  lei314121077 (@来去从心 )
* [x]  [注册中心](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/registry.md) 
  *  [x] [点对点](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/peer2peer.md)
  *  [x] [点对多](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/multiple.md)
  * [x]  [Zookeeper](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/zookeeper.md)
  *  [x] [Etcd](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/etcd.md)
  *  [x] [Consul](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/consul.md)
  * [x]  [mDNS](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/mdns.md)
  * [x]  [进程内调用](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part2/inprocess.md)

## Part Ⅲ 特性 by smallnest (@鸟窝)
* [x]  [编解码](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/codec.md)
* [x]  [失败模式](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/failmode.md)
  * [x]  [Failfast](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/failfast.md)
  * [x]  [Failover](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/failover.md)
  *  [x] [Failtry](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/failtry.md)
  * [x]  [Failbackup](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/failbackup.md)
* [x]  [Fork模式](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/fork.md)
*  [x] [广播模式](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/broadcast.md)
* [x]  [路由](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/selector.md)
  * [x]  [随机选择](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/random_selector.md)
  * [x]  [轮训](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/roundrobin_selector.md)
  * [x]  [一致性哈希](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/hash_selector.md)
  * [x]  [权重](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/weighted_selector.md)
  *  [x] [网络质量优先](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/ping_selector.md)
  *  [x] [地理位置优先](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/geo_selector.md)
  * [x]  [定制路由规则](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/user_selector.md)
* [x]  [超时](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/timeout.md)
* [x]  [元数据](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/metadata.md)
* [x]  [心跳](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/heartbeat.md)
* [x]  [分组](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/group.md)
* [x]  [服务状态](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/state.md)
* [x]  [断路器](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part3/circuit_breaker.md)

## Part Ⅳ 插件 by smallnest  (@鸟窝)
* [x]  [Metrics](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part4/metrics.md)
* [x]  [限流](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part4/rate-limiting.md)
* [x]  [别名](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part4/alias.md)
* [x]  [身份认证](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part4/auth.md)
* [x]  [插件开发](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part4/plugin-dev.md)

## Part Ⅴ 其它 by smallnest  (@鸟窝)
* [x]  [Benchmark](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part5/benchmark.md)
* [x]  [UI管理工具](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part5/ui.md)
* [x]  [协议详解](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part5/protocol.md)

## Part Ⅵ 网关 by smallnest (@鸟窝)
* [x]  [Gateway](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part6/gateway.md)
* [x]  [HTTP 方式调用](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part6/http_invoke.md)
* [x]  [双向通讯](https://github.com/smallnest/go-rpc-programming-guide/tree/master/part6/bidirectional.md)

**Comment by smallnest** [comment]
加comment来认领任务

**Comment by lei314121077** [comment]
Part Ⅱ 注册中心

**Comment by solarhell** [comment]
认领 `Part Ⅰ 开发起步`

**Comment by smallnest** [comment]
认领 `Part Ⅵ 网关`

**Comment by smallnest** [comment]
认领`Part Ⅲ 特性`
